#+title: TOUZA/ppp guide
#+author: SAITO Fuyuki
#+date: <2022-01-26 Wed>

* Introduction
*TOUZA/ppp* is a collection of Fortran subroutines for `parallel
processing procedures', to support MPI.

The original motivation to develop this package is to replace
legacy =xmcomm.F= in MIROC, with improving the interfaces and
the algorithms to control the MPI communicator and the `king' ranks.

*TOUZA/ppp* is maintained by SAITO Fuyuki <saitofuyuki AT jamstec
DOT go DOT jp>.

*TOUZA (楊座)*, MIROC base infrastructure, is a collection of
Fortran procedures mainly adopted in MIROC.  See *TOUZA* README
(expected to be in the parent directory) for general instruction of
*TOUZA* collection.

* Build and installation

* Agent-based hierarchical MPI communicator control
** Agent concept

* Brief description of *TOUZA/ppp* modules
** summary
** =TOUZA_Ppp_amng= - agent manager (mpi communicator control)
*** =init()=
#+begin_src f90
  subroutine init(ierr, u, levv, mode, stdv, icomm, nstack, nagent)
    integer,intent(out)         :: ierr
    integer,intent(in),optional :: u
    integer,intent(in),optional :: levv, mode, stdv
    integer,intent(in),optional :: icomm    ! base MPI communicator
    integer,intent(in),optional :: nstack   ! passed to init_stack()
    integer,intent(in),optional :: nagent   ! passed to init_table()
#+end_src
- =icomm= :: The base MPI communicator for TOUZA library, to pass to
  =TOUZA_Std_mwe= module.
  The base MPI communicator can be set by either this function, or
  direct call of =TOUZA_Std= module family before this function.
  If you want to fine control on the =TOUZA_Std= module, then you may
  have to pass =icomm= not in this function but to =TOUZA_Std=
  initialization functions.
- =nstack= :: Limit number of stacks for agents.  If not present, or
  if less than 1, then the macro =OPT_AGENTS_STACK= is applied.
- =nagent= :: Paremeter to create the hash-table of agents.  If not
  present, the macro =OPT_AGENTS_MAX= times 2 is applied.

*** =query_agent()=
#+begin_src f90
  integer function query_agent(name, iaref)
    character(len=*),intent(in) :: name
    integer,optional,intent(in) :: iaref ! current agent if null
#+end_src
Return agent id corresponding to =NAME=.
Reference agent id =iaref= may be set, and if set =NAME= is searched
among those of the same level, that are one to have the same source
agent.  If not set, the current agent on the top stack is applied.

*** =inquire_agent=
#+begin_src f90
  subroutine inquire_agent &
       & (ierr,   &
       &  agent,  &
       &  irank,  nrank, icomm, igroup, name, ismem)
  subroutine inquire_agent &
       & (ierr,   &
       &  iagent, &
       &  irank,  nrank, icomm, igroup, name, ismem)
    implicit none
    integer,         intent(out)          :: ierr
    character(len=*),intent(in)           :: agent   ! target agent name
    integer,         intent(in), optional :: iagent  ! target agent id
    integer,         intent(out),optional :: irank   ! the rank of calling process on the target agent
    integer,         intent(out),optional :: nrank   ! size of the group associated with the target agent
    integer,         intent(out),optional :: icomm   ! mpi communicator associated with the target agent
    integer,         intent(out),optional :: igroup  ! mpi group associated with the target agent
    character(len=*),intent(out),optional :: name    ! agent identifier string associated with the target agent
    logical,         intent(out),optional :: ismem   ! whether or not the member of target agent
#+end_src
Inquire about properties of a particular agent of =NAME= or
corresponding to a particular id of =IAGENT=.

*** =switch_agent=
#+begin_src f90
  subroutine switch_agent (ierr, iagent)
    integer,intent(out) :: ierr
    integer,intent(in)  :: iagent
#+end_src
*** =push_agent=
#+begin_src f90
  subroutine push_agent (ierr, iagent)
    integer,intent(out) :: ierr
    integer,intent(in)  :: iagent
  subroutine push_agent (ierr, name, iaref, iagent)
    integer,intent(out) :: ierr
    character(len=*),intent(in)  :: name
    integer,optional,intent(in)  :: iaref
    integer,optional,intent(out) :: iagent  ! new agent handle
#+end_src
Switch the agent to =iagent= (by id) or =name= (by name) and push the
agent on the top of the stack.  The argument =NAME= and optional
argument =IAREF=, reference agent id, are passed to =query_agent()=.
When with by-name call, an optional argument =iagent= may be set to
extract the corresponding agent-id of =NAME=.
*** =pop_agent=
#+begin_src f90
  subroutine pop_agent (ierr, iagent)
    integer,intent(out)         :: ierr
    integer,intent(in),optional :: iagent
  subroutine pop_agent (ierr, name, iaref)
    integer,         intent(out) :: ierr
    character(len=*),intent(in)  :: name
    integer,optional,intent(in)  :: iaref
#+end_src
Switch the agent to the one recorded in the stack before the current one.
If =iagent=, or =name= and =iaref= are set, the current top stack is
checked whether not they are identical.  When not, the error is
returned.
The current top stack is popped and discarded.
*** =top_agent=
#+begin_src f90
  subroutine top_agent_ai (ierr, iagent)
    integer,intent(out) :: ierr
    integer,intent(out) :: iagent
#+end_src
Returns current agent id on the top of stack.
*** =new_agent_root=
#+begin_src f90
  subroutine new_agent_root &
       & (ierr, icomm, name, switch)
    integer,         intent(out)         :: ierr
    integer,         intent(in),optional :: icomm
    character(len=*),intent(in),optional :: name
    integer,         intent(in),optional :: switch
#+end_src
Register MPI communicator =ICOMM= as an agent identified as =NAME=.
If =ICOMM= is not set, the base communicator of =TOUZA= library is
used.  If =NAME= is not set, the name is automatically generated.
If an optional argument =switch= is set as non-negative integer,
it is paseed to =switch_agent()= to manipulate the agent stack ---
if zero the top stack is replaced and if positive the agent is pushed
on to the top of stack.

*** =new_agent_color=
#+begin_src f90
  subroutine new_agent_color &
       & (ierr, color, name, src)
    integer,         intent(out)         :: ierr
    integer,         intent(in)          :: color
    character(len=*),intent(in),optional :: name
    integer,         intent(in),optional :: src
    integer,         intent(in),optional :: switch
#+end_src
Split the MPI communicator associated with =SRC= agent id using
=COLOR=, with calling =MPI_Comm_split=.
If =SRC= is not present, the current top agent id on the top stack is
applied.  If =NAME= is present, it is used to identify the new agent,
otherwise it is automatically generated.
If an optional argument =switch= is set as non-negative integer,
it is paseed to =switch_agent()= to manipulate the agent stack.

*** =new_agent_family=
#+begin_src f90
  subroutine new_agent_family &
       & (ierr, drivers, src)
    integer,         intent(out) :: ierr
    character(len=*),intent(in)  :: drivers(:)   ! self drivers to belong to
    integer,optional,intent(in)  :: src
#+end_src
Create communicator family based on the communicator associated with
SRC agent using DRIVERS array.
*** =new_agent_derived=
#+begin_src f90
  subroutine new_agent_derived &
       & (ierr, name, drivers, iagent)
    integer,         intent(out) :: ierr
    character(len=*),intent(in)  :: name         ! new name
    character(len=*),intent(in)  :: drivers(:)   ! derived drivers to belong to
    integer,optional,intent(in)  :: iagent       ! current agent-id if null
#+end_src
Create new derived agent using DRIVERS array.
** =TOUZA_Ppp_king= - king-rank control
*** =get_king= - get KING under AREF agent
#+begin_src f90
  subroutine get_king &
       & (ierr, king, mdl, aref, adef)
    integer,                  intent(out) :: ierr
    integer,                  intent(out) :: king
    character(len=*),         intent(in)  :: mdl
    character(len=*),         intent(in)  :: aref   ! KING reference agent
    character(len=*),optional,intent(in)  :: adef   ! KING definition agent  (same as AREF if null)
#+end_src
*** =set_king=
#+begin_src f90
  subroutine set_king &
       & (ierr, king, pat, adef)
    integer,         intent(out) :: ierr
    integer,         intent(in)  :: king
    character(len=*),intent(in)  :: pat
    character(len=*),intent(in)  :: adef   ! KING definition agent
#+end_src
** =TOUZA_Ppp_miroc= - MIROC =xmcomm= compatible interfaces
* Copyright and license
Copyright 2022 Japan Agency for Marine-Earth Science and Technology
Licensed under the Apache License, Version 2.0
  (https://www.apache.org/licenses/LICENSE-2.0)
