[zbcont]

[zbcont.option]
permute.skip_single = true

[zbcont.keymap]
quit = 'Q'
next_cyclic = 'right'
prev_cyclic = 'left'
next = ' '
prev = 'backspace'
info = 'I'
unmark = 'U'
mark = 'M'
enlarge = '+'
shrink = '-'
reset_geometry = '='
print = 'p'

[zbcont.keymap.figure]
quit = 'q'
duplicate = 'D'
new = 'N'
info = 'i'
mark = 'm'

[zbcont.keymap.coordinate]
next_cyclic = ']'
prev_cyclic = '['
next = ''
prev = ''
transpose = ':'

[zbcont.keymap.file]
next_cyclic = 'f'
prev_cyclic = ''
next = 'F'
prev = ''

[zbcont.keymap.variable]
next_cyclic = 'v'
prev_cyclic = ''
next = 'V'
prev = ''

[zbcont.keymap.record]
next_cyclic = 'r'
prev_cyclic = ''
next = ''
prev = ''
