[zbcont]

[zbcont.Legacy3]
# geometry = [10.45, 7.39]
# contour_text.fontsize = ""
# title_text.fontsize = ""

[zbcont.Legacy3.rect]
# body =  [0.129, 0.225, 0.830, 0.585]
# colorbar = [0.061, 0.070, 0.245, 0.057]

[zbcont.Legacy3.cbar_major]
# labelsize = ""

[zbcont.ContourPlot]

[zbcont.option]
permute.skip_single = true
resize_step = 0.25

[zbcont.keymap]
quit = 'Q'
next_cyclic = 'right'
prev_cyclic = 'left'
next = ' '
prev = 'backspace'
info = 'I'
unmark = 'U'
mark = 'M'
enlarge = '+'
shrink = '-'
reset_geometry = '='
print = 'p'
toggle_clabel = 'c'
toggle_cmap = 'C'

[zbcont.keymap.figure]
quit = 'q'
duplicate = 'D'
new = 'N'
info = 'i'
mark = 'm'

[zbcont.keymap.coordinate]
next_cyclic = ']'
prev_cyclic = '['
next = ''
prev = ''
transpose = ':'

[zbcont.keymap.file]
next_cyclic = 'f'
prev_cyclic = ''
next = 'F'
prev = ''

[zbcont.keymap.variable]
next_cyclic = 'v'
prev_cyclic = ''
next = 'V'
prev = ''

[zbcont.keymap.record]
next_cyclic = 'r'
prev_cyclic = ''
next = ''
prev = ''
