[zbcont]

# [Legacy3]
# geometry = [20.0, 10.0]

[Legacy3.guide]
color = 'red'
alpha = 0.7
linewidth = 8.0

# [zbcont.Legacy3.colorbar.major]
# # labelsize = ""

# [zbcont.Legacy3.info]

[zbcont.ContourPlot]

[zbcont.option]
permute.skip_single = true
resize_step = 0.25
ignore_alt = true
scroll_unit = 1.5

[zbcont.output]
name = 'zbtFigure.png'
gsep = '-'
nsep = '_'

[zbcont.mouse.body]
select_h = 'left'
select_hv = 'middle'
select_v = 'right'
anchor_h = 'shift+left'
anchor_hv = 'shift+middle'
anchor_v = 'shift+right'
next_cyclic  = 'fwd'
prev_cyclic  = 'bwd'

[zbcont.mouse.axis]
next_cyclic = 'left'
prev_cyclic = 'right'
next = ''
prev = ''
transpose = 'middle'

[zbcont.mouse.spine]
select = 'left'
anchor = 'shift+left'
reverse = 'middle'
next_norm = 'right'
# next_cyclic = 'left'
# lock = 'middle'

[zbcont.mouse.colorbar]
next_cyclic = 'left'
prev_cyclic = ''
next_group = 'right'
prev_group = ''
reverse = 'middle'

[zbcont.mouse.spine.colorbar]
lock = 'middle'

[zbcont.mouse.info]
lock = 'middle'

[zbcont.keymap]
quit = 'Q'
next_cyclic = 'right'
prev_cyclic = 'left'
next = ' '
prev = 'backspace'
unmark = 'U'
mark = 'M'
enlarge = '+'
shrink = '-'
sync_geometry = '='
reset_geometry = ','
print = 'p'
toggle_clabel = 'c'
turn_cmap = 'C'
turn_norm = 'N'
redraw = '.'
reverse_horizontal = '#'
reverse_vertical = '%'
entire_view = 'w'
rewind = '0'
turn_inner_0 = '1'
turn_inner_1 = '2'
turn_inner_2 = '3'
turn_inner_3 = '4'
toggle_turn = '5'
next_outer_0 = '9'
next_outer_1 = '8'
next_outer_2 = '7'
next_outer_3 = '6'
animate = 'a'

# [zbcont.keymap.colorbar]
# next_cyclic = 'C'
# prev_cyclic = ''
# next_norm = ''
# prev_norm = ''
# transpose = ''

[zbcont.keymap.figure]
quit = 'q'
duplicate = 'D'
new = 'ctrl+n'
refresh = 'ctrl+r'
info = 'i'
info_detail = 'I'
mark = 'm'

[zbcont.keymap.coordinate]
next_cyclic = '['
prev_cyclic = ']'
next = ''
prev = ''
transpose = ':'

x.next_cyclic = ''
x.prev_cyclic = ''
x.next = ''
x.prev = ''

y.next_cyclic = ''
y.prev_cyclic = ''
y.next = ''
y.prev = ''

[zbcont.keymap.anchor]
next_cyclic = '('
prev_cyclic = ')'
next = ''
prev = ''
clear = '!'

[zbcont.keymap.file]
next_cyclic = 'f'
next = 'F'

[zbcont.keymap.variable]
next_cyclic = 'v'
next = 'V'

# next_inner_4 = '5'

# [zbcont.keymap.record]
# next_cyclic = 'r'
# prev_cyclic = ''
# next = ''
# prev = ''
