#+title: Common installation guide of TOUZA sub-packages
#+author: SAITO Fuyuki
#+date: <2020-06-07 Sun>
#+email: saitofuyuki@jamstec.go.jp

* Introduction
  *TOUZA* sub-package may be distributed as a stand-alone package, or
  a part of *TOUZA* (*楊座*), /MIROC/ base infrastructure.  For the
  latter case, you can ignore this guide.

* *TOUZA* sub-package set-up as a stand alone package
** autotool files
   Unless the package contains configuration file such as =configure=,
   =Makefile.in=, etc, you need to generate these files first.  This
   is the case when you are using a git version of the source, or when
   trying to extract the package from *TOUZA* package.  =autogen.sh=
   in this package or in *TOUZA* can help you generate them.

   : % sh ./autogen.sh   ## dry-run
   : ./autogen.sh: dry-run
   : If you are sure, run as ./autogen.sh -y
   : :
   : % sh ./autogen.sh -y ## wet-run
   : :

** build
   For generic installation instructions please see the =INSTALL= file.

   In short:

   : % ./configure --help

   to read the usage, and:

   : % ./configure
   : % make
   : % make install
   : % make install-mod

   for typical installation.  After a series of commands a library
   file will be installed in =PREFIX/lib=.

   Depending on compiler, =*.mod= files are generated for each module,
   which are necessary to be installed somewhere the compiler can
   find.  If configure is successful, the last command will install
   =*.mod= files into =$(pkglibdir)= (default is
   =PREFIX/lib/touza_PKG=).  You can control the directory at
   configure time by using

   : % ./configure --enable-install-modules=/SOMEWHERE/DIR
   : % ./configure --disable-install-modules    # to skip installation

** build dependencies among sub-packages
   There may be build-dependencies among sub-packages.  =configure=
   try its best to find required *TOUZA* sub-packages, but it is not
   perfect.  When a build process fails somewhere, try =configure=
   with set the path explicitly.  For example, *TOUZA/cal* depends on
   *TOUZA/std*.  If *TOUZA/std* is built or installed in an unusual
   directory, try as follows:

   : % ./configure --with-touza-std=SOMEWHERE/std ......
