#+title: TOUZA guide
#+author: SAITO Fuyuki
#+date: <2023-03-09>
#+email: saitofuyuki AT jamstec DOT go DOT jp

* Introduction
*TOUZA (楊座)*, MIROC base infrastructure, is a collection of
Fortran procedures mainly adopted in MIROC.

* Installation
** distribution
Latest *TOUZA* can be obtained at [[https://github.com/saitofuyuki/touza]].

** autotool files
Unless the package contains configuration file such as =configure=,
=Makefile.in=, etc, you need to generate these files first.  This
is a typical case when you are using a git version of the source.
=autogen.sh= in this package can help you generate them.

: % sh ./autogen.sh -h       ## show help
: ./autogen.sh: batch to generate auto-files
: :
: :
: % sh ./autogen.sh          ## dry-run
: ./autogen.sh: dry-run
: If you are sure, run as ./autogen.sh -y
: :
: % sh ./autogen.sh -y       ## wet-run
: % sh ./autogen.sh -y -c    ## wet-run; clear old files
: % sh ./autogen.sh -y -c -m ## wet-run; clear old files; copy missing files

You need following tools to generate the autotool scripts.  Older
versions of these tools may work as expected, though not checked.

- GNU autoconf (2.71 or later)
- GNU automake (1.16.5 or later)
- GNU libtool (2.4.6 or later)
- GNU autoconf archive (2022-09-03 or later)
  - Small changes in ax_lib_netcdf4.m4 was necessary, which was
    already included in the vendor package after 2022-07-28.
- pkgconf (1.8.1 or later)
  - pkg-config may work

** build
For generic installation instructions please see the =INSTALL= file.

In short:

: % ./configure --help

to read the usage, and:

: % ./configure --with-build-jmz --enable-nctcdf
: % make
: % make install

for typical installation.  With the argument =--with-build-jmz= you
can build sample program to use =TOUZA= such as =chak=.
With the =--enable-nctcdf= very simple NetCDF output feature is
included.

After a series of commands, a script, library, and headers will be
installed under =PREFIX= and =EPREFIX=.

: PREFIX
: |-- include
: |   |-- touza.h
: |   |-- :         header files
: `-- share
:     `-- touza
:         |-- ax_lib_netcdf4.m4
:         |-- :                      m4 macro files
:         |-- calendar_coco.F90      switcher sources to export to MIROC, COCO
:         |-- calendar_miroc.F90
:         |-- div_miroc.F90
:         |-- nio_miroc.F90
:         `-- ppp_miroc.F90
: EPREFIX
: |-- bin
: |   `-- chak
: |-- include
: |   `-- touza
: |       |-- test_div_layout_utils.mod
: |       |   :                     module files (compiler dependent)
: `-- lib
:     |-- libtouza.a
:     |-- libtouza.la
:     `-- pkgconfig
:         `-- touza.pc

Depending on compiler, =*.mod= files are generated for each module,
which are necessary to be installed somewhere the compiler can
find (e.g., gfortran).  If configure is successful, =*.mod= files
are installed into =EPREFIX/include/touza=, which can be controlled
with =--enable-install-modules= at =configure=.

** system-dependent features
*** ifort
Need =-heap-arrays= option in =FCFLAGS= and =FFLAGS=, which must be
set at configure.  An example follows:

: % ./configure FCFLAGS='-g -O2 -heap-arrays' FFLAGS='-g -O2 -heap-arrays'

*** some pkgconf quotes the output
Old pkgconf quotes the output, which leads to error at compilation.

If you found something like below in Makefile,
: NETCDF4_LDFLAGS = "-L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/usr/lib/x86_64-linux-gnu"
please manually remove the quotation, such as:
: NETCDF4_LDFLAGS = -L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/usr/lib/x86_64-linux-gnu

* Copyright and license
Copyright 2020-2024 Japan Agency for Marine-Earth Science and Technology
Licensed under the Apache License, Version 2.0
  (https://www.apache.org/licenses/LICENSE-2.0)
